#
# Copyright 2020 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Default environment. But we still try to be explicit when specifying the test environment for each runtime test.
os: linux
dist: focal

language: python

matrix:
  include:
    - python: "3.6"
      os: linux
      dist: xenial
    - python: "3.7"
      os: linux
      dist: bionic
    - python: "3.8"
      os: linux
      dist: focal
    - python: "3.9"
      os: linux
      dist: focal
    - python: "pypy3"
      os: linux
      # The prebuilt pypy packages at https://antocuni.github.io/pypy-wheels/ don't work with the older default dist
      dist: focal
    - name: "Lint"
      python: "3.8"
      env: TOXENV=lint

install:
  - pip install tox-travis

script:
  - tox -vv

# Build master branch only
branches:
  only:
    - master
